config/routes.rb
Rails.application.routes.draw do

  get 'user-profile' => "users#user-profile"
  get 'users-admin' => "admins#users-admin"
  get 'products-admin' => "admins#products-admin"
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout', to: "sessions#destroy"
  api_version(:module => "V1", :path => {:value => "v1"}) do
    resources :products
    resources :users
  end  
  
  resources :products
  resources :users
  resources :admins
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	mount_uploader :image, AvatarUploader
	has_secure_password
	validates :email, presence: true
	validates :password, presence: true
	validates :password_confirmation, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/concerns/template_response.rb
module TemplateResponse
	def success_response(data, message = '', status= 200)
	  render json: {data: data, status: status, message: message} 
	end

	def error_response(data, message = '', status= 500)
	 	render json: {data: data, status: status, message: message} 
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_id, only: [:edit,:update,:new,:destroy]
  def index
  end

  def show
  end

  def new
      @product = Product.new
  end

  def create
      @product = Product.new product_params
      if @product.save 
        redirect_to products_admin_path
      else
        render :new
      end
  end

  def edit

  end

  def update
    if @product.update product_params
      redirect_to products_admin_path
    else
      render :edit
    end
  end

  def destroy
  end
  def find_id
    @product = Product.find_by id: params[:id]
  end
  def product_params
    params.require(:product).permit(:name,:description,:category,:price,:quality)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create 
  	@user = User.find_by email: params[:session][:email].downcase
    if @user && @user.authenticate(params[:session][:password])
    	log_in @user
    	redirect_to root_path
    else
      render :new
    end
  end
  def destroy
  	log_out
  	redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_id, only: [:edit,:show,:update,:destroy] 
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def show
  end

  def update
    if @user.update user_full_params
      redirect_to users_admin_path
    else 
      render :edit
    end
  end

  def destroy
  end
  def find_id
    @user = User.find_by id: params[:id]
  end
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:address,:numberphone)
  end
  def user_full_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:address,:numberphone,:role)
  end
end

app/controllers/v1/base_controller.rb
class V1::BaseController < ApplicationController
	include TemplateResponse
end

app/controllers/v1/products_controller.rb
class V1::ProductsController < V1::BaseController
	before_action :find_id, only: [:show,:edit,:destroy]
	def index
		page = params[:page]
		per = params[:per]
		@products = Product.page(page).per(per)
		data = ActiveModel::Serializer::CollectionSerializer.new(@products, each_serializer: ProductSerializer)
		success_response data, "asdasd" 
	end
	def show
		success_response @product, "asdasd" 	
	end
	def new
		
	end
	def create
	  @product = Product.new product_params
	  if @product.save
			success_response @product, "created"
		else
			error_response "not created"
	  end
	end

	def edit
	    
		success_response @product, "asdasd" 
	end
	def update
    if @product.update product_params
      success_response @product, "updated"
    else
    	error_response "not updated"
    end
	end
	def destroy
    if @product.destroy
      success_response @product, "deleted"
    else
      error_response "not updated"
    end
	end
	def product_params
		params.require(:product).permit(:name,:description,:image,:price,:quality,:category)
	end
	def find_id
		@product = Product.find_by id: params[:id]
	end

end

app/controllers/v1/users_controller.rb
class V1::UsersController < V1::BaseController
	def index
		@users = User.all
		data = ActiveModel::Serializer::CollectionSerializer.new(@users, each_serializer: UserSerializer)
		success_response data, "asdasd" 
	end
	def show
		@user = User.find_by id: params[:id]
		success_response @user, "asdasd" 
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title page_title = ""
		base_title = "Shop Clothes"
		if page_title.empty?
			base_title
		else 
			page_title + " | " + base_title
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user] = user
  end	
  def log_out
  	session[:user] = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<div class="header-admin">
    <div class="header-admin-1">
        <div class="title-admin">
            <h3><%= link_to "Shop Clothes",root_path  %></h3>
        </div>
        <% if session[:user].present? %>
            <div class="dropdown">
                <%= image_tag( "tra.jpg", :alt => "icon", :class => " avt-admin" ) %>
            </div>
        <% end %>
    </div>
</div>
<div class="content-admin">
    <div class="content-admin-1">
        <div class="content-admin-left">
            <ul class="menu-admin">
                <li><%= link_to "Dashboard",admins_path  %></li>
                <li><%= link_to "User", users_admin_path  %></li>
                <li><%= link_to "Product", products_admin_path  %></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
            </ul>
        </div>
        <div class="content-admin-right">
            <div class="crumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><%= link_to "Dashboard", admins_path %></li>
                    </ol>
                </nav>
            </div>
            <div class="view">
                <div class="view-total">
                    <div class="show-total">
                        <div class="total-user">
                        </div>
                    </div>
                    <button class="btn bt-user">View-User</button>
                </div>
                <div class="view-total product-right">
                    <div class="show-total">
                        <div class="total-product">
                        </div>
                    </div>
                    <button class="btn bt-product">View-Product</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $.ajax({
        url: Routes.v1_products_path(),
        type: 'GET',
        dataType: 'json',
        success: function(data){
            var x =0;
            $(data).each(function(index,el){
                for(var i in el['data']){
                    x++;
                }
                console.log(x);
                var totalproduct = $('.total-product');
                totalproduct.append(x+' Products');
            })
        }

    })
    $.ajax({
        url: Routes.v1_users_path(),
        type: 'GET',
        dataType: 'json',
        success: function(data){
            var x =0;
            $(data).each(function(index,el){
                for(var i in el['data']){
                    x++;
                }
                console.log(x);
                var totalproduct = $('.total-user');
                totalproduct.append(x+' Users');
            })
        }

    })
    $(document).ready(function(){
        $('.bt-user').click(function(){
            window.location.href = Routes.users_admin_path();
        });
        $('.bt-product').click(function(){
            window.location.href =Routes.products_admin_path();
        });
    });
</script>

app/views/admins/products-admin.html.erb
<div class="header-admin">
    <div class="header-admin-1">
        <div class="title-admin">
            <h3>Admin Page Shop Clothes</h3>
        </div>
        <div class="account">
            <img src="iconshop.png" alt="" width="50px" height="50px">
        </div>  
    </div>
</div>
<div class="content-admin">
    <div class="content-admin-1">
        <div class="content-admin-left">
            <ul class="menu-admin">
                <li><%= link_to "Home",admins_path  %></li>
                <li><%= link_to "User", users_admin_path  %></li>
                <li><%= link_to "Product", products_admin_path  %></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
            </ul>
        </div>
        <div class="content-admin-right">
             <div class="crumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><%= link_to "Dashboard", admins_path %></li>
                        <li class="breadcrumb-item active valuename" aria-current="page" >List Products</li>
                    </ol>
                </nav>
             </div>
            <table class="table">
                <thead>
                    <tr>
                            <th scope="col"></th>
                            <th scope="col">name</th>
                            <th scope="col">description</th>
                            <th scope="col">category</th>
                            <th scope="col">price</th>
                            <th scope="col">quality</th>
                            <th scope="col">image</th>
                            <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody class="trElment">

                </tbody>
            </table>
            <button class="btn insert-product"> Insert Product </button>
        </div>
    </div>
</div>
<script type="text/javascript">
    $.ajax({
        url: Routes.v1_products_path(),
        type: 'GET',
        dataType: 'json',
        success: function(data){
            var x=0,name,description,category,price,quality,image;
            $(data).each(function(index,el){
                for (var i in el['data']){
                x++;
                id = el['data'][i].id;
                name = el['data'][i].name;
                description = el['data'][i].description;
                category = el['data'][i].category;
                price = el['data'][i].price;
                quality = el['data'][i].quality;
                image = el['data'][i].image;

                var tdNameElement = $('<td></td>');
                tdNameElement.html(name);

                var tdDesElement = $('<td></td>');
                tdDesElement.html(description);

                var tdCateElement = $('<td></td>');
                tdCateElement.html(category);

                var tdPriceElement = $('<td></td>');
                tdPriceElement.html(price);

                var tdQuaElement = $('<td></td>');
                tdQuaElement.html(quality);

                var tdImageElement = $('<td></td>');
                var imagex = $('<img style="width:50px;">')
                imagex.attr({
                    'src': image,
                    'class': 'imageproduct'
                })
                tdImageElement.append(imagex);

                var tdxElement = $('<td></td>');
                tdxElement.html(x);

                var tdUpdateElement = $('<td></td>');
                var iconUpdate = $('<i class="fa fa-pencil-square-o update-product" aria-hidden="true"></i>');
                iconUpdate.attr({
                  'ten': id
                });
                tdUpdateElement.append(iconUpdate);

                var tdDeleteElement = $('<td></td>');

                var iconDelete = $('<i class="fa fa-trash-o delete-product" aria-hidden="true"></i>');
                iconDelete.attr({
                  'ten': id
                })
                tdDeleteElement.append(iconDelete);

                var trElment = $('<tr></tr>');
                trElment.append(tdxElement);
                trElment.append(tdNameElement);
                trElment.append(tdDesElement);
                trElment.append(tdCateElement);
                trElment.append(tdPriceElement);
                trElment.append(tdQuaElement);
                trElment.append(tdImageElement);
                trElment.append(tdUpdateElement);
                trElment.append(tdDeleteElement);

                var tx = $('.trElment');
                tx.append(trElment);
                console.log(el)
              }            
          });
        }
    });
</script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.update-product').click(function(){
            var id = $(this).attr('ten');
            window.location.href = Routes.edit_product_path(id);
        });
        $('.insert-product').click(function(){
            window.location.href = Routes.new_product_path(id);
        });
        $('.delete-product').click(function(){
            window.location.href =Routes.product_path();
        })
    })
</script>

app/views/admins/users-admin.html.erb
<div class="header-admin">
    <div class="header-admin-1">
        <div class="title-admin">
            <h3>Admin Page Shop Clothes</h3>
        </div>
        <div class="account">
            <img src="iconshop.png" alt="" width="50px" height="50px">
        </div>  
    </div>
</div>
<div class="content-admin">
    <div class="content-admin-1">
        <div class="content-admin-left">
            <ul class="menu-admin">
                <li><%= link_to "Home",admins_path  %></li>
                <li><%= link_to "User", users_admin_path  %></li>
                <li><%= link_to "Product", products_admin_path  %></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
            </ul>
        </div>
        <div class="content-admin-right">
            <div class="crumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><%= link_to "Dashboard", admins_path %></li>
                        <li class="breadcrumb-item active valuename" aria-current="page" >List Users</li>
                    </ol>
                </nav>
             </div>
            <table class="table">
                <thead>
                    <tr>
                      <th scope="col"></th>
                      <th scope="col">Name</th>
                      <th scope="col">Address</th>
                      <th scope="col">Email_Address</th>
                      <th scope="col">Numberphone</th>
                      <th scope="col">Role</th>
                      <th scope="col">Avatar</th>
                      <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody class="trElment">

                </tbody>
            </table>
            <button class="btn insert-user"> Insert User </button>
        </div>
    </div>
</div>
<script type="text/javascript">
    $.ajax({
        url: Routes.v1_users_path(),
        type: 'GET',
        dataType: 'json',
        success: function(data){
            $(data).each(function(index,el){
              var x = 0,name,address,email_address,numberphone;
              for (var i in el['data']){
                x++;
                id = el['data'][i].id;
                name = el['data'][i].name;
                address = el['data'][i].address;
                email_address = el['data'][i].email;
                numberphone = el['data'][i].numberphone;
                role = el['data'][i].role;
                image = el['data'][i].image;
    
                var tdNameElement = $('<td></td>');
                tdNameElement.html(name);

                var tdAddressElement = $('<td></td>');
                tdAddressElement.html(address);

                var tdEmailElement = $('<td></td>');
                tdEmailElement.html(email_address);

                var tdNumberElement = $('<td></td>');
                tdNumberElement.html(numberphone);

                var tdRoleElement = $('<td></td>');
                tdRoleElement.html(role);

                var tdxElement = $('<td></td>');
                tdxElement.html(x);

                var tdImageElement = $('<td></td>');
                var imagex = $('<img style="width:50px;">')
                imagex.attr({
                  'src':image
                })

                var tdUpdateElement = $('<td></td>');
                var iconUpdate = $('<i class="fa fa-pencil-square-o update-user" aria-hidden="true"></i>');
                iconUpdate.attr({
                  'ten': id
                });
                tdUpdateElement.append(iconUpdate);

                var tdDeleteElement = $('<td></td>');
                var iconDelete = $('<i class="fa fa-trash-o delete-user" aria-hidden="true"></i>');
                iconDelete.attr({
                  'ten': id
                })
                tdDeleteElement.append(iconDelete);

                tdImageElement.append(imagex);
                var trElment = $('<tr></tr>');
                trElment.append(tdxElement);
                trElment.append(tdNameElement);
                trElment.append(tdAddressElement);
                trElment.append(tdEmailElement);
                trElment.append(tdNumberElement);
                trElment.append(tdRoleElement);
                trElment.append(tdImageElement);
                trElment.append(tdUpdateElement);
                trElment.append(tdDeleteElement);

                var tx = $('.trElment');
                tx.append(trElment);
                console.log(role)
              }
              

            });
        }
    }); 
</script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.update-user').click(function(){
            var id = $(this).attr('ten');
            window.location.href = Routes.edit_user_path(id);
        });
        $('.insert-user').click(function(){
            window.location.href = Routes.new_user_path(id);
        });
        $('.delete-user').click(function(){
            window.location.href =Routes.user_path();
        })
    })
</script>

app/views/layouts/_header.html.erb
<div class="header">
		<div class="content-header">
			<div class="icon1">
				<div class="image-title">
					<%= link_to image_tag("iconshop.png", :alt => "icon"), root_path %>
				</div>
				<div class="title-header">
					<h3><%= link_to "Shop Clothes", root_path %>
				</div>
			</div>
			<div class="search">
				<div class="form-group12">
					<input type="text" name="search" id="search" class="form-control input-lg valuesearch" placeholder="Search" tabindex="3">
				</div>
		    </div>
			<div class="menu">
				<ul class="menu1">
					<li>
					<% if session[:user].present? %>
						<div class="dropdown">
							<%= image_tag( "tra.jpg", :alt => "icon", :class => "header-icon1 js-show-header-dropdown dropdown-toggle avt" ,data: { toggle: 'dropdown' } ) %>
						    <ul class="dropdown-menu">
						      <li><%= link_to "Infor", user_profile_path %></li>
						      <li><%= link_to "Log out", logout_path, method: :delete %></li>
						    </ul>
						</div>
					<% else %>
						<div class="dropdown">
							<%= image_tag("icon-header-01.png", :alt => "icon", :class => "header-icon1 js-show-header-dropdown dropdown-toggle" ,data: { toggle: 'dropdown' } ) %>
						    <ul class="dropdown-menu">
						      <li><%= link_to "Sign in", login_path %></li>
						      <li><%= link_to "Sign up", new_user_path %></li>
						    </ul>
						</div>
					<%end%>
					</li>
					<li>
						<%= image_tag("icon-header-02.png") %>
					</li>
					<% if session[:user].present? %>
					<% if session[:user]['role']== "admin" %>
						<li><%= link_to "Admin", admins_path %></li>
						<%end%>
					<%end%>
				</ul>	
			</div>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
	<h2>Update Product</h2>
	<div class="row1">
		<div class="khungrow">
			<%= form_for @product do |form| %>
		    <div class="form-group1">
		      	<div class="row-left">
		      		<%= form.label "Full name" %>
		      	</div>
		      	<div class="row-right">
		      	  <%= form.text_field :name, class: 'form-control' %>
		      	</div>
		    </div>
		    <div class="form-group1">
			    <div class="row-left">
			   		<%= form.label "Description" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :description, class: 'form-control' %>
		      	</div>
		    </div>
		    <div class="form-group1">
			    <div class="row-left">
			   		<%= form.label "Category" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :category, class: 'form-control' %>
		      	</div>
		    </div>
		    <div class="form-group1">
		    	<div class="row-left">
			   		<%= form.label "Price" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :price, class: 'form-control' %>
		      	</div>
		    </div>
		    <div class="form-group1">
		    	<div class="row-left">
			   		<%= form.label "Quality" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :quality, class: 'form-control' %>
		      	</div>
		    </div>
		    <div class="form-group1"> 
		     <%= form.submit "Update", class: 'btn btn-default btn-regis' %>       
				</div>
			<% end %>
		</div>
	</div>

app/views/products/index.html.erb
<% provide(:title, "") %>
	<!-- header -->
	<%= render 'layouts/header' %>
	<!-- carousel -->
	
	<div id="demo" class="carousel slide" data-ride="carousel">
		<ul class="carousel-indicators">
		  <li data-target="#demo" data-slide-to="0" class="active"></li>
		  <li data-target="#demo" data-slide-to="1"></li>
		  <li data-target="#demo" data-slide-to="2"></li>
		</ul>
		<div class="carousel-inner">
		  <div class="carousel-item active">
		  	<%= image_tag("thoitrang.jpg", :alt => "Fashion" ) %>
		  </div>
		  <div class="carousel-item">
		  	<%= image_tag("thoitrang.jpg", :alt => "Fashion" ) %>
		  </div>
		  <div class="carousel-item">
		   	<%= image_tag("thoitrang.jpg", :alt => "Fashion" ) %>
		  </div>
		</div>
	</div>
	<!-- content -->
	<div class="content">
		<div class="category">
			<div class="ct-left">
				<div class="ct-left1">
					<%= image_tag("thoitrangnu.jpg", :alt => "Woman" , :class => "category1" ) %>
				</div>	
			</div>
			<div class="ct-right">
				<div class="ct-right1">
					<%= image_tag("thoitrangnam.jpg", :alt => "Man" , :class => "category1" ) %>
				</div>
			</div>
		</div>	
		<div class="content3">
			<div class="ct-title2">
					<h1>Không Thể Bỏ Qua</h1>	
			</div>
		</div>
		<br>
		<div class="sanpham"> 
			<div class="khungsanpham"> 
			</div>
		</div>	
	</div>

																																																																																																																																																																																																																																																																																													
	<div class="clearfix"></div>
	<div class="footer">
		<div class="footerleft">
			<div class="footer1">
				<a href=""><h3>Shop Clothes</h3></a>
				<a href=""><p>Review shop</p></a>
				<a href=""><p>About</p></a>
				<a href=""><p>Infor</p></a>
			</div>
		</div>
		<div class="footercenter">
			<div class="footer2">
				<a href=""><h3>Công Ty TNHH 1 Thành Viên </h3></a>
				<p>SDT:0111111111</p>
				<p>Diachi:LOL</p>
				<a href="#"><%= image_tag("iconfb.png", :alt => "Man" ) %></a>
				<a href="#"><%= image_tag("iconzalo.png", :alt => "Man" ) %></a>
			</div>
		</div>
		<div class="footerright">
			
		</div>
		<div id="peopleList"></div>

		<script id="personTmpl" type="text/x-jsrender">
		  <label>Name:</label> {{:name}}<br/>
		</script>
	</div>	
	<script type="text/javascript">
		var page = 1;
		var per = 4;
	  $.ajax({
	    url: 'http://localhost:3000/v1/products',
	    type: 'GET',
	    data: {page: page, per: per},
	    dataType: 'json',
	    success: function(data){
	    	var khungSanPham = $('.khungsanpham');
	    	$(data).each(function(index, el) {
	      	for (var i in el['data']) {
	      		var id = el['data'][i].id;
	      		var image = el['data'][i].image;
	      		var name = el['data'][i].name;
	      		var price = el['data'][i].price;
	      		var divRow = $('<div></div>');
	      		divRow.attr('class', 'row-sanpham');

	      		var aElement = $('<a></a>');
	      		aElement.attr('href', '');
	      		divRow.append(aElement);
	      		var divAnhSanPham = $('<div class="anhsanpham"></div>');
	      	
	      		var img = $('<img>');
	      		img.attr({
	      			'src': image,
	      			'alt': "asd"
	      		});
	      		divAnhSanPham.append(img);
	      		aElement.append(divAnhSanPham);

	      		var divTen = $('<div class="tensanpham"></div>');
	      		divTen.html(name);
	      		divRow.append(divTen);

	      		var divGiaSanPham = $('<div class="giasanpham"></div>')
	      		divGiaSanPham.html(price +" d");
	      		divRow.append(divGiaSanPham);

	      		var divBtMua = $('<div class="btmua"></div>');
	      		var button = $('<button  name="btmua" >Mua</button> ');
	      		button.attr({
	      			'ten' : id,
	      			'class': 'btn btn-default button-mua'
	      		});
	      		divBtMua.append(button);
	      		divRow.append(divBtMua);
	      		khungSanPham.append(divRow);
	      		// var imagesanpham = $('.imagesanpham');
	      		// imagesanpham.attr({
	      		// 	'src': image,
	      		// 	'alt': "asd"
	      		// });
	      		// var tensanpham = $('.tensanpham');
	      		// tensanpham.html(name);
	      		// var giasanpham = $('.giasanpham');
	      		// giasanpham.html(price);
	      		console.log(el)
	      	}
	      });
	    }
	  });
	</script>
	<script type="text/javascript">
		$(document).ready(function(){	
			$(document).on('click', '.button-mua', function(){
				var id = $(this).attr('ten');
				window.location.href=Routes.product_path(id);
			});
		});
		
	</script>
</body>
</html>

app/views/products/new.html.erb
	<h2>Insert Product</h2>
	<div class="row1">
		<div class="khungrow">
			<%= form_for @product do |form| %>
		    <div class="form-group1">
		      	<div class="row-left">
		      		<%= form.label "Full name" %>
		      	</div>
		      	<div class="row-right">
		      	  <%= form.text_field :name, class: 'form-control', placeholder: 'Full name' %>
		      	</div>
		    </div>
		    <div class="form-group1">
			    <div class="row-left">
			   		<%= form.label "Description" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :description, class: 'form-control', placeholder: 'Description' %>
		      	</div>
		    </div>
		    <div class="form-group1">
			    <div class="row-left">
			   		<%= form.label "Category" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :category, class: 'form-control', placeholder: 'category' %>
		      	</div>
		    </div>
		    <div class="form-group1">
		    	<div class="row-left">
			   		<%= form.label "Price" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :price, class: 'form-control', placeholder: 'price' %>
		      	</div>
		    </div>
		    <div class="form-group1">
		    	<div class="row-left">
			   		<%= form.label "Quality" %>
			   	</div>
		      	<div class="row-right">
		      		<%= form.text_field :quality, class: 'form-control', placeholder: 'quality' %>
		      	</div>
		    </div>
		    <div class="form-group1"> 
		     <%= form.submit "Create", class: 'btn btn-default btn-regis' %>       
				</div>
			<% end %>
		</div>
	</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>